apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}
      external_labels:
        cluster: {{ .Values.clusterName | default "k8s-cluster" }}

    scrape_configs:
    {{- range .Values.prometheus.scrapeConfigs }}
      - job_name: {{ .jobName | quote }}
        {{- if .metricsPath }}
        metrics_path: {{ .metricsPath | quote }}
        {{- end }}
        {{- if .scrapeInterval }}
        scrape_interval: {{ .scrapeInterval }}
        {{- end }}
        static_configs:
          - targets:
            {{- range .targets }}
              - {{ . | quote }}
            {{- end }}
        {{- if .relabelConfigs }}
        relabel_configs:
          {{- toYaml .relabelConfigs | nindent 10 }}
        {{- end }}
    {{- end }}

  alert.rules.yaml: |-
    groups:
    {{- range .Values.prometheus.alertRules }}
      - name: {{ .name | quote }}
        rules:
        {{- range .rules }}
          - alert: {{ .alert | quote }}
            expr: {{ .expr | quote }}
            for: {{ .for }}
            labels:
              severity: {{ .labels.severity | quote }}
            annotations:
              summary: {{ .annotations.summary | quote }}
              description: {{ .annotations.description | quote }}
        {{- end }}
    {{- end }}
