apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "prometheus.name" . }}-allow-scrape
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9090
