apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus.name" . }}-rolebinding
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.name" . }}
roleRef:
  kind: Role
  name: {{ include "prometheus.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
