apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "{{ .Values.elasticsearch.service.url }}" ]
    server.ssl.enabled: true
    server.ssl.certificate: /tls/tls.crt
    server.ssl.key: /tls/tls.key
