apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kibana-role
  labels:
    app: kibana
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
