apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-rolebinding
  labels:
    app: kibana
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kibana.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: kibana-role
  apiGroup: rbac.authorization.k8s.io
