apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: 5601
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kibana
