apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fleet-server-hpa
  labels:
    app: fleet-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: fleet-server
  minReplicas: {{ .Values.fleetServer.hpa.minReplicas }}
  maxReplicas: {{ .Values.fleetServer.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fleetServer.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fleetServer.hpa.targetMemoryUtilizationPercentage }}
