apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-server-role
  labels:
    app: fleet-server
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
