apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic-stack.fullname" . }}-elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: "elastic-cluster"
    node.name: ${HOSTNAME}
    discovery.seed_hosts: ["${HOSTNAME}"]
    cluster.initial_master_nodes: ["${HOSTNAME}"]
    network.host: 0.0.0.0
    bootstrap.memory_lock: true
