apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elastic-stack.fullname" . }}-elasticsearch
  labels:
    app: {{ include "elastic-stack.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "elastic-stack.fullname" . }}-elasticsearch
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "elastic-stack.fullname" . }}-elasticsearch
  apiGroup: rbac.authorization.k8s.io
