apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elastic-stack.fullname" . }}-elasticsearch
  labels:
    app: {{ include "elastic-stack.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
