apiVersion: v1
kind: Service
metadata:
  name: {{ include "elastic-stack.fullname" . }}-elasticsearch
  labels:
    app: {{ include "elastic-stack.name" . }}
    component: elasticsearch
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  clusterIP: None
  selector:
    app: {{ include "elastic-stack.name" . }}
    component: elasticsearch
