# jenkins-service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: kube-system  # or another namespace if Jenkins runs elsewhere
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployer-cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: kube-system  # same as above
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
