apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yourchart.fullname" . }}-blackbox-config
  labels:
    app: {{ include "yourchart.name" . }}
    component: blackbox-exporter
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          method: GET
          headers:
            User-Agent: blackbox-exporter
          tls_config:
            insecure_skip_verify: false
