# Global Configuration
cloudProvider: "" # e.g., aws | azure | gcp; injected by Jenkins
storageClassMap:
  aws: gp2
  azure: managed-premium
  gcp: standard

tls:
  enabled: true
  secretName: kibana-tls

# ========================
# Elasticsearch Settings
# ========================
elasticsearch:
  enabled: true
  replicas: 3
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.13.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 50Gi
    storageClassName: ""
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 75

# ========================
# Kibana Settings
# ========================
kibana:
  replicaCount: 2

  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 8.7.1
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer

  persistence:
    size: 10Gi
    storageClassName: "standard"

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  serviceAccount:
    name: kibana-sa

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75

  annotations:
    enabled: true


# ========================
# Fleet Server Settings
# ========================
fleetServer:
  replicaCount: 2

  image:
    repository: docker.elastic.co/beats/elastic-agent
    tag: 8.7.1
    pullPolicy: IfNotPresent

  persistence:
    size: 10Gi
    storageClassName: "standard"

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  serviceAccount:
    name: fleet-server-sa

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75

  annotations:
    enabled: true


# ========================
# Elastic Agent Settings
# ========================
elasticAgent:
  image:
    repository: docker.elastic.co/beats/elastic-agent
    tag: 8.7.1
    pullPolicy: IfNotPresent

  serviceAccount:
    name: elastic-agent-sa

  fleet:
    insecure: false

  enrollmentToken: "YOUR_ENROLLMENT_TOKEN_HERE"

  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

  annotations:
    enabled: true


# ========================
# Namespace and Monitoring Settings
# ========================
namespace: monitoring

networkPolicy:
  enabled: true

rbac:
  create: true

serviceAccount:
  create: true
  name: elastic-stack-sa
