{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: coredns-rules
  labels:
    role: alert-rules
    prometheus: kube-prometheus
spec:
  groups:
    - name: coredns.rules
      rules:
        - alert: CoreDNSDown
          expr: up{job="coredns"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "CoreDNS is down"
            description: "CoreDNS service is not responding on {{ $labels.instance }}"
{{- end }}
