{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-rules
  labels:
    role: alert-rules
    prometheus: kube-prometheus
spec:
  groups:
    - name: node.rules
      rules:
        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node down"
            description: "Node {{ $labels.instance }} is down for more than 5 minutes."
{{- end }}
