apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail
  labels:
    app: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
roleRef:
  kind: Role
  name: promtail
  apiGroup: rbac.authorization.k8s.io