apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail
  labels:
    app: promtail
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]