apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  labels:
    app: elastic-agent
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
      annotations:
        {{- if .Values.elasticAgent.annotations.enabled }}
        {{ toYaml .Values.elasticAgent.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.elasticAgent.serviceAccount.name }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: elastic-agent
          image: "{{ .Values.elasticAgent.image.repository }}:{{ .Values.elasticAgent.image.tag }}"
          imagePullPolicy: {{ .Values.elasticAgent.image.pullPolicy }}
          env:
            - name: FLEET_SERVER_HOST
              value: {{ .Values.fleetServer.service.url | quote }}
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ELASTIC_AGENT_FLEET_ENROLL
              value: "true"
            - name: ELASTIC_AGENT_FLEET_URL
              value: {{ .Values.fleetServer.service.url | quote }}
            - name: ELASTIC_AGENT_FLEET_INSECURE
              value: "{{ .Values.elasticAgent.fleet.insecure }}"
          volumeMounts:
            - name: dockersocket
              mountPath: /var/run/docker.sock
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /usr/share/elastic-agent/config
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
        - name: config
          configMap:
            name: elastic-agent-config
