apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: elastic-agent-hpa
  labels:
    app: elastic-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: elastic-agent
  minReplicas: {{ .Values.elasticAgent.hpa.minReplicas }}
  maxReplicas: {{ .Values.elasticAgent.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.elasticAgent.hpa.targetCPUUtilizationPercentage }}
