apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-agent-rolebinding
  labels:
    app: elastic-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Values.elasticAgent.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: elastic-agent-role
  apiGroup: rbac.authorization.k8s.io
