apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent-role
  labels:
    app: elastic-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints", "persistentvolumeclaims", "events", "namespaces"]
    verbs: ["get", "watch", "list"]
