apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasource
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.grafana.datasource.prometheusUrl | quote }}
        isDefault: true
        editable: false
