apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc }}
