apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-exporter
  labels:
    app: node-exporter
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/metrics"]
    verbs: ["get", "list", "watch"]