apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-exporter
  labels:
    app: node-exporter
subjects:
  - kind: ServiceAccount
    name: node-exporter
roleRef:
  kind: Role
  name: node-exporter
  apiGroup: rbac.authorization.k8s.io