apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas | default 3 }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch
              topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: {{ .Values.elasticsearch.resources.requests.memory | default "2Gi" }}
              cpu: {{ .Values.elasticsearch.resources.requests.cpu | default "1" }}
            limits:
              memory: {{ .Values.elasticsearch.resources.limits.memory | default "4Gi" }}
              cpu: {{ .Values.elasticsearch.resources.limits.cpu | default "2" }}
          livenessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=1s
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=1s
              port: 9200
            initialDelaySeconds: 10
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage.size | default "10Gi" }}
        {{- if .Values.elasticsearch.storageClass }}
        storageClassName: {{ .Values.elasticsearch.storageClass }}
        {{- end }}
