apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  namespace: elastic
spec:
  replicas: {{ .Values.fleetServer.replicas | default 1 }}  # Default to 1 replica if not specified
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
    spec:
      containers:
        - name: fleet-server
          image: "{{ .Values.fleetServer.image.repository }}:{{ .Values.fleetServer.image.tag }}"  # Image versioning from values.yaml
          args: ["run", "--fleet-server"]
          env:
            - name: FLEET_SERVER_ENABLE
              value: "1"
            - name: FLEET_ENROLL
              value: "1"
            - name: FLEET_URL
              value: "{{ .Values.fleetServer.fleetUrl }}"  # Dynamic Fleet URL
            - name: FLEET_ENROLLMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fleet-enrollment-token
                  key: token
          resources:
            requests:
              memory: "{{ .Values.fleetServer.resources.requests.memory | default '512Mi' }}"  # Default memory requests
              cpu: "{{ .Values.fleetServer.resources.requests.cpu | default '500m' }}"  # Default CPU requests
            limits:
              memory: "{{ .Values.fleetServer.resources.limits.memory | default '1Gi' }}"  # Default memory limits
              cpu: "{{ .Values.fleetServer.resources.limits.cpu | default '1' }}"  # Default CPU limits
