apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  namespace: elastic
spec:
  serviceName: kibana
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic.svc.cluster.local:9200"
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
  volumeClaimTemplates:
    - metadata:
        name: kibana-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.kibana.storage.size | default "10Gi" }}
        {{- if .Values.kibana.storageClass }}
        storageClassName: {{ .Values.kibana.storageClass }}
        {{- end }}
