apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
spec:
  type: {{ .Values.kibana.service.type | default "LoadBalancer" }}  # LoadBalancer for external access
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
