apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager
  labels:
    app: alertmanager
subjects:
  - kind: ServiceAccount
    name: alertmanager
roleRef:
  kind: Role
  name: alertmanager
  apiGroup: rbac.authorization.k8s.io