apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-secret
  labels:
    app: alertmanager
type: Opaque
stringData:
  smtp_user: {{ .Values.alertmanager.smtp.username | quote }}
  smtp_pass: {{ .Values.alertmanager.smtp.password | quote }}
