{{- if and .Values.hpa.enabled .Values.hpa.loki.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loki-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: loki
  minReplicas: {{ .Values.hpa.loki.minReplicas }}
  maxReplicas: {{ .Values.hpa.loki.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.loki.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.loki.targetMemoryUtilizationPercentage }}
{{- end }}
