apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki
  labels:
    app: loki
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]