apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
    spec:
      serviceAccountName: {{ .Values.kubeStateMetrics.serviceAccount.name }}
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
            - name: telemetry
              containerPort: 8081
          resources:
            {{- toYaml .Values.kubeStateMetrics.resources | nindent 12 }}
