apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubeStateMetrics.serviceAccount.name }}
roleRef:
  kind: Role
  name: kube-state-metrics
  apiGroup: rbac.authorization.k8s.io
