apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
