{{- if .Values.servicemonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: web
      interval: 15s
{{- end }}
