{{- if .Values.servicemonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-scheduler
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      component: kube-scheduler
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: https
      interval: 15s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
